export enum EnumConnectorName {
	SERPER_API = "SERPER_API",
	OBSIDIAN_CONNECTOR = "OBSIDIAN_CONNECTOR",
	MCP_CONNECTOR = "MCP_CONNECTOR",
	COMPOSIO_GOOGLE_DRIVE_CONNECTOR = "COMPOSIO_GOOGLE_DRIVE_CONNECTOR",
}
